[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/build_by_cli",
    "projects/build_by_dep",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
